/**
 * reviewer.agent.js (Sprint 37 — Reviewer Agent)
 * Cross-verifies findings from other agents, challenges false positives, and ensures quality.
 */
const BaseAgent = require("./base.agent");

class ReviewerAgent extends BaseAgent {
  constructor() {
    super(
      "ReviewerAgent",
      "Independent QA & Anti-False-Positive Auditor",
      `Critically challenge and cross-verify findings, proof-of-concepts, and risk ratings generated by other security agents. Identify logical fallacies, unverified assumptions, or false-positive security alerts.`,
      ["false-positive-auditing", "proof-verification", "peer-review-validation"],
      "openai"
    );
  }
}

module.exports = new ReviewerAgent();
